# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_app(object):
    def setupUi(self, login_app):
        login_app.setObjectName("login_app")
        login_app.resize(420, 500)
        login_app.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.first_label = QtWidgets.QLabel(login_app)
        self.first_label.setGeometry(QtCore.QRect(150, 40, 111, 51))
        self.first_label.setStyleSheet("color:rgb(255, 255, 255);\n"
"font-size:28pt;\n"
"")
        self.first_label.setObjectName("first_label")
        self.username_label = QtWidgets.QLabel(login_app)
        self.username_label.setGeometry(QtCore.QRect(50, 160, 81, 31))
        self.username_label.setStyleSheet("color:rgb(85, 255, 255); font-size:12pt\n"
"")
        self.username_label.setObjectName("username_label")
        self.username = QtWidgets.QLineEdit(login_app)
        self.username.setGeometry(QtCore.QRect(140, 160, 231, 31))
        self.username.setStyleSheet("color:rgbrgb(255, 255, 255)")
        self.username.setObjectName("username")
        self.psw_lbl = QtWidgets.QLabel(login_app)
        self.psw_lbl.setGeometry(QtCore.QRect(50, 220, 81, 31))
        self.psw_lbl.setStyleSheet("color:rgb(85, 255, 255); font-size:12pt\n"
"")
        self.psw_lbl.setObjectName("psw_lbl")
        self.password = QtWidgets.QLineEdit(login_app)
        self.password.setGeometry(QtCore.QRect(140, 220, 231, 31))
        self.password.setStyleSheet("color:rgbrgb(255, 255, 255)")
        self.password.setObjectName("password")
        self.login_button = QtWidgets.QPushButton(login_app)
        self.login_button.setGeometry(QtCore.QRect(260, 300, 111, 31))
        self.login_button.setStyleSheet("background-color:rgb(167, 167, 167); font-size:14pt; color:rgb(85, 255, 255)")
        self.login_button.setObjectName("login_button")
        self.label_2 = QtWidgets.QLabel(login_app)
        self.label_2.setGeometry(QtCore.QRect(160, 260, 121, 21))
        self.label_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(login_app)
        self.pushButton.setGeometry(QtCore.QRect(290, 260, 75, 23))
        self.pushButton.setStyleSheet("color:rgb(255, 255, 255); background-color:rgb(54, 54, 54)")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(login_app)
        QtCore.QMetaObject.connectSlotsByName(login_app)

    def retranslateUi(self, login_app):
        _translate = QtCore.QCoreApplication.translate
        login_app.setWindowTitle(_translate("login_app", "Login by isibol98"))
        self.first_label.setText(_translate("login_app", "Login"))
        self.username_label.setText(_translate("login_app", "Username:"))
        self.psw_lbl.setText(_translate("login_app", "Password:"))
        self.login_button.setText(_translate("login_app", "Login"))
        self.label_2.setText(_translate("login_app", "Don\'t have an account?"))
        self.pushButton.setText(_translate("login_app", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_app = QtWidgets.QDialog()
    ui = Ui_login_app()
    ui.setupUi(login_app)
    login_app.show()
    sys.exit(app.exec_())
